name: Lancer Streamlit via Ngrok

on:
  workflow_dispatch:  # Permet de déclencher manuellement le workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Installer les dépendances
      run: |
        python -m pip install --upgrade pip
        pip install streamlit pyngrok
        pip install -r requirements.txt

    - name: Installer Ngrok
      run: |
        wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        unzip ngrok-stable-linux-amd64.zip
        chmod +x ngrok
        sudo mv ngrok /usr/local/bin/

    - name: Démarrer Ngrok et Streamlit
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      run: |
        # Authentification Ngrok
        ngrok authtoken $NGROK_AUTH_TOKEN
        
        # Démarrer Ngrok en arrière-plan
        ngrok http 8501 > /dev/null &
        
        # Attendre que Ngrok soit prêt
        sleep 5
        
        # Récupérer l'URL publique
        NGROK_URL=$(curl -s localhost:4040/api/tunnels | jq -r .tunnels[0].public_url)
        
        # Afficher l'URL
        echo "🌐 URL Publique Ngrok: $NGROK_URL"
        
        # Démarrer Streamlit
        streamlit run app/mmm_dashboard.py &
        
        # Garder le workflow actif
        sleep 1h
