name: Deploy to Streamlit Cloud

on:
  push:
    branches: [ main ]  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install streamlit-cloud-push
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Deploy to Streamlit Cloud
        run: |
          streamlit_cloud_push deploy \
            --app-name ${{ github.repository_owner }}-${{ github.event.repository.name }} \
            --branch main \
            --main-file app.py
        env:
          STREAMLIT_CLOUD_TOKEN: ${{ secrets.STREAMLIT_CLOUD_TOKEN }}
